use role SYSADMIN;
--CUSTOMERS
create or replace table COREBANK.RAW.CUST(
    CUST_ID VARCHAR,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    GENDER VARCHAR,
    DOB DATE,
    CREATED_AT TIMESTAMP
);